version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - redis_db
  redis_db:
    build: redis_db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data